server:
  #https端口号.
  port: 80
  ssl:
    #证书的路径.
    key-store: classpath:keystore.p12
    #证书密码，请修改为您自己证书的密码.
    key-store-password: 123456
    #秘钥库类型
    keyStoreType: PKCS12
    #证书别名
    keyAlias: tomcat

thymeleaf:
  cache: false
  prefix: classpath:/templates/ # ???templates????html??
  suffix: .html
  encoding: UTF-8
  mode: HTML5
